apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: flask
  name: flask
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    protocol: TCP
  selector:
    io.kompose.service: flask
status:
  loadBalancer: {}
