apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: master
  name: master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: master
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: master
    spec:
      containers:
      - env:
        - name: SPARK_MODE
          value: master
        image: palomagomez/practica-master:2.0.0
        imagePullPolicy: IfNotPresent
        name: master
        ports:
        - containerPort: 4040
        - containerPort: 6066
        - containerPort: 7077
        - containerPort: 8080
        - containerPort: 7001
        - containerPort: 7002
        - containerPort: 7003
        - containerPort: 7004
        - containerPort: 7005
        resources: {}
      hostname: master
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
