apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-express
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo-express
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo-express
    spec:
      containers:
      - image: mongo-express:0.54
        imagePullPolicy: IfNotPresent
        name: mongo-express
        ports:
        - containerPort: 8081
          protocol: TCP
        resources: {}
      hostname: mongo-express
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
