apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-deployment
  labels:
    app: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      containers:
      - name: master
        image: bitnami/spark:2.4.4
        ports:
        - containerPort: 27017